### PR TITLE
Don't crash on missing result

### PR DESCRIPTION
**Pull request by ChrisBr**
I saw these errors on a branch. It doesn't seem to happen all the time though.

image

### CODE REVIEW

**Comment by casperisfine** [comment]
Hum, I'd feel more confortable if we understood what's going on. This PR seem to just put the error under the rug, no?

**Comment by ChrisBr** [comment]
Seems not to be a huge problem but it's anyway a good idea to have this early return.

**Review by casperisfine — APPROVED** [review]
Nevermind, I didn't notice we were in `ensure`.

**Comment by ChrisBr** [comment]
> Hum, I'd feel more confortable if we understood what's going on. This PR seem to just put the error under the rug, no?

Yeah so it was my mistake because I patched the `run` method and did not return the result. 

```ruby
def run(*)
  super

  puts "GC stats...."
end
```

But I think it's still a good idea to have an early return here, no? Can it be possible the yield does not return a result here?

**Review by richardnuno — APPROVED** [review]
Avoiding the return in the ensure seems like a good suggestion but looks good.

**Comment by kim76** [comment]
@ChrisBr did you want to merge this or close it?

**Comment by ChrisBr** [comment]
Richard fixed it in https://github.com/Shopify/ci-queue/pull/178

**Pull request closed without merging**
